version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - autocinema-net

  # PgAdmin para PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - autocinema-net

  # MySQL principal
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: autocine
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: Rafaelmorales2024
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - autocinema-net

  
  # Microservicios AutocineNova
  autocinema-home:
    build: ./autocinema-home
    container_name: autocinema-home
    depends_on:
      - mysql
    ports:
      - "8001:8001"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-usuarios:
    build: ./autocinema-usuarios
    container_name: autocinema-usuarios
    depends_on:
      - mysql
    ports:
      - "8002:8002"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-pelicula:
    build: ./autocinema-pelicula
    container_name: autocinema-pelicula
    depends_on:
      - mysql
    ports:
      - "8003:8003"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-sede:
    build: ./autocinema-sede
    container_name: autocinema-sede
    depends_on:
      - mysql
    ports:
      - "8004:8004"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-sala:
    build: ./autocinema-sala
    container_name: autocinema-sala
    depends_on:
      - mysql
    ports:
      - "8005:8005"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-reclamo:
    build: ./autocinema-reclamo
    container_name: autocinema-reclamo
    depends_on:
      - mysql
    ports:
      - "8006:8006"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-metodopago:
    build: ./autocinema-metodopago
    container_name: autocinema-metodopago
    depends_on:
      - mysql
    ports:
      - "8007:8007"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-funciones:
    build: ./autocinema-funciones
    container_name: autocinema-funciones
    depends_on:
      - mysql
    ports:
      - "8008:8008"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-estacionamiento:
    build: ./autocinema-estacionamiento
    container_name: autocinema-estacionamiento
    depends_on:
      - mysql
    ports:
      - "8009:8009"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-confiteria:
    build: ./autocinema-confiteria
    container_name: autocinema-confiteria
    depends_on:
      - mysql
    ports:
      - "8010:8010"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-categoria:
    build: ./autocinema-categoria
    container_name: autocinema-categoria
    depends_on:
      - mysql
    ports:
      - "8011:8011"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  autocinema-boletos:
    build: ./autocinema-boletos
    container_name: autocinema-boletos
    depends_on:
      - mysql
    ports:
      - "8012:8012"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

  # API Gateway
  autocinema-gateway:
    build: ./autocinema-gateway
    container_name: autocinema-gateway
    depends_on:
      - autocinema-home
      - autocinema-usuarios
      - autocinema-pelicula
      - autocinema-sede
      - autocinema-sala
      - autocinema-reclamo
      - autocinema-metodopago
      - autocinema-funciones
      - autocinema-estacionamiento
      - autocinema-confiteria
      - autocinema-categoria
      - autocinema-boletos
    ports:
      - "9191:9191"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - autocinema-net

networks:
  autocinema-net:
    driver: bridge

volumes:
  db_data:
  mysql_data:
  workbench_files: